### ISSUE TITLE
how to set serverTimezone for MySQL8

### ISSUE THREAD

**Issue by 564155611** [javthon/mybatis-generator-yml-maven-plugin#3]
**Describe the bug**
![image](https://user-images.githubusercontent.com/73692902/145703346-e3a6d74b-b0a4-44ee-b5c4-47b1e1228146.png)
my project:[04_oversell](https://github.com/564155611/elastic-lock/tree/master/04_distributelock)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by javthon** [comment]
Busy with work these days, I'll look into the issue when free, thanks for your feedback

**Comment by 564155611** [comment]
> Busy with work these days, I'll look into the issue when free, thanks for your feedback

After I set the db parameters as in the figure below, the problem no longer occurs.
![image](https://user-images.githubusercontent.com/73692902/145708968-7598c12e-61d2-433e-b1bc-f444c6cd1971.png)

**Comment by javthon** [comment]
> > Busy with work these days, I'll look into the issue when free, thanks for your feedback
> 
> After I set the db parameters as in the figure below, the problem no longer occurs. ![image](https://user-images.githubusercontent.com/73692902/145708968-7598c12e-61d2-433e-b1bc-f444c6cd1971.png)

Good
